[package]
name = "axbacktrace"
version = "0.1.0"
edition = "2021"
authors = ["WeiKang Guo  <guoweikang.kernel@gmail.com>"] 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
log = "0.4"
cfg-if = "1.0"
